FROM node:18-alpine

WORKDIR /app

ARG VITE_MOBILE_BASE_URL
ARG VITE_BACKEND_URL

ENV VITE_MOBILE_BASE_URL=$VITE_MOBILE_BASE_URL
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

EXPOSE 8080
CMD ["npm", "run", "start"]
